import fs from 'node:fs';
import path from 'node:path';

const root=path.resolve(process.env.PROJECT_ROOT||'.');
const read=file=>JSON.parse(fs.readFileSync(path.join(root,file),'utf8'));
const config=read('data/authored/integrated-foundation-scenarios-v0.2.json');
const modernRules=read('data/authored/modern-formation-rules-v0.1.json');
const political=read('data/authored/escalation-occupation-rules-v0.1.json');
const operational=read('data/authored/operational-combat-rules-v0.1.json');
const territories=read('data/generated/systems/territory-logistics-baseline-v0.1.json');
const land=read('data/generated/maps/adjacency-land-v0.3.json');
const routes=read('data/generated/maps/routes-provisional-v0.3.json');
const byId=new Map(territories.map(t=>[t.territory_id,t]));
const adjacency=structuredClone(land);
for(const r of routes){if(!adjacency[r.from].includes(r.to))adjacency[r.from].push(r.to);if(!adjacency[r.to].includes(r.from))adjacency[r.to].push(r.from);}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const percentile=(v,p)=>{const s=[...v].sort((a,b)=>a-b);return s[Math.round((s.length-1)*p)];};
function rng(seed){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296;};}
function stageFor(value){return[...political.global_escalation.thresholds].reverse().find(t=>value>=t.value)||{id:'local_response',value:0,enemy_power_multiplier:1,supply_multiplier:1};}
function frontier(controlled,targeted=new Set()){const out=new Set();for(const id of controlled.keys())for(const n of adjacency[id])if(!controlled.has(n)&&!targeted.has(n))out.add(n);return[...out];}
function targetOrder(ids){return ids.map(id=>byId.get(id)).sort((a,b)=>(b.baseline_supply_capacity+b.primary_hub_capacity)-(a.baseline_supply_capacity+a.primary_hub_capacity)||a.territory_id.localeCompare(b.territory_id));}
function terrainFactor(t){return['mountainous','subarctic'].includes(t.terrain_class)?1.3:t.terrain_class==='mixed-upland'?1.16:1;}
function urbanFactor(t){return({low:.88,medium:1,high:1.14,'very-high':1.28}[t.urbanisation]||1);}
function makeFuture(personnel,start){const out=[];for(let i=1,left=personnel;left>0;i+=1){const n=Math.min(config.task_group_size,left),full=Math.round(n*.9);out.push({id:`TG-${i}`,kind:'future',personnel:n,initial:n,full,damaged:n-full,unarmoured:0,location:start,cohesion:90,readiness:90,status:'idle',availableDay:0,killed:0,captured:0,casualties:0});left-=n;}return out;}
function occupation(id,day,policy){return{id,captureDay:day,policy,legitimacy:policy.initial_legitimacy,resistance:policy.initial_resistance,supplyDamage:0,raised:false};}
function occupationState(x,day){if(day-x.captureDay<x.policy.administration_delay_days)return'contested';if(x.legitimacy>=58&&x.resistance<=28)return'integrated';if(x.legitimacy>=40&&x.resistance<=45)return'administered';return'controlled';}
function mobilisationEligible(x,day,strategy){const state=occupationState(x,day);if(day-x.captureDay<x.policy.local_force_delay_days)return false;if(strategy.id==='restrained')return state==='integrated';if(strategy.id==='pragmatic')return state==='administered'||state==='integrated';return state!=='contested';}
function modernRole(t){if(t.primary_hub_capacity>=4)return'combined-arms';if(['high','very-high'].includes(t.urbanisation))return'mechanised';if(t.urbanisation==='medium')return'infantry';return'security';}
function makeModern(x,day,index){const t=byId.get(x.id),role=modernRole(t),available=modernRules.available_personnel_by_urbanisation[t.urbanisation]*modernRules.mobilisable_share_by_urbanisation[t.urbanisation],n=Math.round(Math.min(modernRules.formation_personnel,available));return{id:`MF-${x.id}-${index}`,kind:'modern',nation:x.id.split('-')[0],origin:x.id,personnel:n,initial:n,equipment:100,role,location:x.id,cohesion:72,readiness:68,loyalty:clamp(modernRules.loyalty.initial_base+x.policy.modern_loyalty_modifier,0,100),status:'idle',availableDay:day,killed:0,captured:0,casualties:0,defected:false,refusals:0};}
function futurePower(f,supply){return(f.full*4.6+f.damaged*3.5+f.unarmoured*1.35)/1000*f.cohesion/100*f.readiness/100*Math.max(.25,supply);}
function modernPower(f,supply,target){const command=f.nation===target.split('-')[0]?1:adjacency[f.location]?.includes(target)?.9:.78;return f.personnel/1000*config.modern_power_per_1000*modernRules.roles[f.role].combat_factor*f.equipment/100*f.cohesion/100*f.readiness/100*command*Math.max(.4,supply);}
function accepts(f,target,random){const command=f.nation===target.split('-')[0]?'national':adjacency[f.location]?.includes(target)?'adjacent':'expeditionary';const threshold=command==='expeditionary'?modernRules.order_thresholds.attack_expeditionary:modernRules.order_thresholds.attack_adjacent;return f.loyalty*.55+f.cohesion*.2+f.readiness*.15+modernRules.command_friction[command]*10+random()*10>=threshold;}
function removeArmour(f,count){let left=count;for(const key of ['unarmoured','damaged','full']){const n=Math.min(left,f[key]);f[key]-=n;left-=n;}f.personnel=f.full+f.damaged+f.unarmoured;}
function applyCasualties(f,count){const actual=Math.min(f.personnel,Math.max(0,count));if(f.kind==='future')removeArmour(f,actual);else f.personnel-=actual;f.casualties+=actual;return actual;}
function damageArmour(f,count){if(f.kind!=='future')return 0;const fromFull=Math.min(f.full,Math.round(count*.72)),fromDamaged=Math.min(f.damaged,Math.max(0,count-fromFull));f.full-=fromFull;f.damaged+=fromFull-fromDamaged;f.unarmoured+=fromDamaged;return fromDamaged;}
function supplyState(controlled,formations,day,stage){let capacity=0;for(const x of controlled.values()){const t=byId.get(x.id),age=day-x.captureDay,activation=clamp(x.policy.supply_activation_share+(1-x.policy.supply_activation_share)*age/14,0,1);capacity+=t.baseline_supply_capacity*config.supply_capacity_per_point*activation*(1-x.supplyDamage);}capacity*=1-political.civilian_needs.protected_capacity_share;const demand=formations.filter(f=>!f.defected).reduce((s,f)=>s+f.personnel*(f.kind==='modern'?modernRules.roles[f.role].supply_demand:1),0);return clamp(capacity*stage.supply_multiplier/Math.max(1,demand),0,1);}

function run(startId,mode,strategy,seedIndex){
  const random=rng(mode.future_personnel*37+strategy.id.length*1009+seedIndex*99991+startId.split('').reduce((s,c)=>s+c.charCodeAt(0),0)*89),policy=political.occupation_policies[strategy.occupation_policy];
  const controlled=new Map([[startId,occupation(startId,0,policy)]]),future=makeFuture(mode.future_personnel,startId),modern=[],formations=[...future],battles=[],medical=[],brokenPool={suits:0,parts:mode.future_personnel*config.initial_parts_per_suit};
  let day=0,completed=null,defeat=null,escalation=2,peakEscalation=2,lowestSupply=1,battlesWon=0,battlesLost=0,modernLed=0,resistanceIncidents=0,uprisings=0,lostTerritories=0,foreignReinforcements=0,nuclearRiskDays=0,technologyExposure=0,modernRefusals=0,modernDefections=0;
  while(day<config.simulation_days&&!completed&&!defeat){
    day+=1;
    for(const item of medical.filter(m=>m.day===day)){const f=formations.find(x=>x.id===item.id);if(!f||f.defected)continue;f.personnel+=item.personnel;if(f.kind==='future'){const armoured=Math.round(item.personnel*item.armourReturn);f.damaged+=armoured;f.unarmoured+=item.personnel-armoured;}f.cohesion=clamp(f.cohesion+5,0,90);}
    for(const x of [...controlled.values()]){
      x.legitimacy=clamp(x.legitimacy+x.policy.daily_legitimacy_change,0,100);x.resistance=clamp(x.resistance+x.policy.daily_resistance_change,0,100);
      if(random()<x.resistance/100*political.resistance.incident_daily_chance_at_100){resistanceIncidents+=1;x.supplyDamage=clamp(x.supplyDamage+political.resistance.incident_supply_damage,0,.55);escalation+=political.resistance.incident_escalation;}
      if(x.resistance>=political.resistance.uprising_threshold&&x.legitimacy<=political.resistance.uprising_legitimacy_threshold&&random()<political.resistance.uprising_daily_chance){uprisings+=1;escalation+=political.resistance.suppression_escalation;if(random()<.25&&!battles.some(b=>b.origin===x.id)){controlled.delete(x.id);lostTerritories+=1;continue;}}
      if(!x.raised&&mobilisationEligible(x,day,strategy)){const count=Math.max(1,Math.ceil(modernRules.available_personnel_by_urbanisation[byId.get(x.id).urbanisation]*modernRules.mobilisable_share_by_urbanisation[byId.get(x.id).urbanisation]/modernRules.formation_personnel));for(let i=1;i<=count;i+=1){const f=makeModern(x,day,i);modern.push(f);formations.push(f);}x.raised=true;}
    }
    const territorialFloor=political.global_escalation.territorial_control_floor_scale*Math.pow(controlled.size/territories.length,1.45);escalation=Math.max(territorialFloor,escalation-political.global_escalation.daily_decay*(.7+strategy.humanitarian_priority));let stage=stageFor(escalation);
    if(escalation>=political.global_escalation.us_reinforcement_threshold&&day%political.global_escalation.us_reinforcement_interval_days===0)foreignReinforcements+=1;
    if(escalation>=political.global_escalation.nuclear_risk_threshold){nuclearRiskDays+=1;const risk=clamp(political.global_escalation.nuclear_base_daily_risk+(escalation-political.global_escalation.nuclear_risk_threshold)/8*political.global_escalation.nuclear_max_daily_risk,0,political.global_escalation.nuclear_max_daily_risk);if(random()<risk){defeat='general-killed-in-strategic-strike';break;}}
    const rawSupply=supplyState(controlled,formations,day,stage),portalReserve=Math.max(0,(10-day)/10),supply=clamp(rawSupply+portalReserve,.3,1),combatSupply=supply;lowestSupply=Math.min(lowestSupply,supply);
    if(supply<.72){for(const x of controlled.values()){x.legitimacy=clamp(x.legitimacy-political.civilian_needs.shortage_legitimacy_loss_per_day*(1-supply),0,100);x.resistance=clamp(x.resistance+political.civilian_needs.shortage_resistance_gain_per_day*(1-supply),0,100);}escalation+=controlled.size*political.civilian_needs.shortage_escalation_per_territory_day*(1-supply);}
    if(strategy.humanitarian_priority>.5&&day%12===0&&controlled.size>3){const x=[...controlled.values()].sort((a,b)=>a.legitimacy-b.legitimacy)[0];x.legitimacy=clamp(x.legitimacy+4,0,100);x.resistance=clamp(x.resistance-3,0,100);escalation-=.8*strategy.humanitarian_priority;}
    for(const f of formations.filter(f=>!f.defected)){
      if(f.status==='recovering'&&day>=f.availableDay){f.status='idle';f.cohesion=clamp(f.cohesion+10,0,f.kind==='future'?90:85);f.readiness=clamp(f.readiness+8,0,f.kind==='future'?90:80);}
      if(f.kind==='future'){const wear=Math.min(f.full,Math.round(f.personnel*config.daily_armour_wear_share*(supply<.34?2:supply<.67?1.4:1)));f.full-=wear;f.damaged+=wear;if(f.status==='idle'){const repair=Math.min(f.damaged,Math.floor(f.initial*config.daily_repair_share*Math.max(.2,supply)),Math.floor(brokenPool.parts/config.repair_parts_cost));f.damaged-=repair;f.full+=repair;brokenPool.parts-=repair*config.repair_parts_cost;}}
      else{if(supply<.34&&day%5===0)f.loyalty-=modernRules.loyalty.unsupplied_daily_loss*(1-supply);if(f.status==='idle'){f.personnel=Math.min(f.initial*.85,f.personnel+Math.ceil(f.initial*modernRules.casualty_replacement.daily_share));f.readiness=clamp(f.readiness+.35,0,80);}if(f.loyalty<modernRules.loyalty.defection_threshold){f.defected=true;f.status='defected';modernDefections+=1;}}
    }
    for(const battle of [...battles]){
      const attackers=battle.attackers.map(id=>formations.find(f=>f.id===id)).filter(f=>f&&!f.defected&&f.personnel>0),attackerPower=attackers.reduce((s,f)=>s+(f.kind==='future'?futurePower(f,combatSupply):modernPower(f,combatSupply,battle.target)),0)*(0.9+random()*.2),enemyPower=battle.enemyPower*(0.92+random()*.16),ratio=attackerPower/Math.max(.1,enemyPower);
      const lossMultiplier=ratio<.8?1.55:ratio>1.35?.72:1;for(const f of attackers){const rate=(f.kind==='future'?config.future_daily_casualty_share:config.modern_daily_casualty_share)*lossMultiplier*stage.enemy_power_multiplier*(.85+random()*.3),loss=applyCasualties(f,Math.round(f.personnel*rate));battle.casualties[f.id]=(battle.casualties[f.id]||0)+loss;if(f.kind==='future')battle.broken+=damageArmour(f,Math.round(f.personnel*config.future_armour_damage_share*lossMultiplier*(.85+random()*.3)));else f.equipment=clamp(f.equipment-loss/f.initial*100*modernRules.roles[f.role].equipment_loss_factor,0,100);f.cohesion=clamp(f.cohesion+(ratio>=1.25?2:ratio>=.85?-5:-13),0,100);f.readiness=clamp(f.readiness-1.5,0,100);}
      battle.progress+=clamp((ratio-1)*38+28,-35,45);battle.days+=1;const forced=attackers.length===0||attackers.some(f=>f.cohesion<operational.withdrawal.default_cohesion_threshold)||attackers.reduce((s,f)=>s+f.personnel,0)<config.minimum_future_commitment;let outcome=null;if(battle.progress>=100)outcome='victory';else if(battle.progress<=-80||forced||battle.days>=10)outcome=forced||battle.progress<20?'withdrawal':'victory';
      if(outcome){const holds=outcome==='victory',medicalRules=operational.medical_outcomes[holds?'holds_battlefield':forced?'rout':'ordered_retreat'];for(const f of attackers){const total=battle.casualties[f.id]||0,killed=Math.round(total*medicalRules.killed),captured=Math.round(total*medicalRules.captured),recoverable=Math.round(total*medicalRules.recoverable),critical=Math.round(total*medicalRules.critical);f.killed+=killed;f.captured+=captured;medical.push({id:f.id,personnel:recoverable,day:day+operational.medical_return_days.recoverable_wounded,armourReturn:holds?.7:.35},{id:f.id,personnel:critical,day:day+operational.medical_return_days.critical_wounded,armourReturn:holds?.55:.2});f.status='recovering';f.availableDay=day+(holds?3:6);f.location=holds?battle.target:battle.origin;if(f.kind==='modern')f.loyalty+=holds?modernRules.loyalty.victory_gain:-modernRules.loyalty.defeat_loss;}
        const salvage=operational.salvage_recovery[holds?'holds_battlefield':forced?'rout':'ordered_retreat'],recovered=Math.round(battle.broken*salvage);brokenPool.suits+=recovered;brokenPool.parts+=recovered*.4;technologyExposure+=battle.broken-recovered;escalation+=(battle.broken-recovered)*operational.technology_capture_escalation_per_suit*.02;
        if(holds){controlled.set(battle.target,occupation(battle.target,day,policy));battlesWon+=1;if(battle.modernPowerAtStart>battle.futurePowerAtStart)modernLed+=1;escalation+=policy.capture_escalation+policy.civilian_harm*political.global_escalation.civilian_harm_scale;if(random()<strategy.infrastructure_destruction_chance)escalation+=political.global_escalation.critical_infrastructure_destroyed;if(random()<strategy.technology_loss_chance){escalation+=political.global_escalation.future_technology_capture;technologyExposure+=1;}}else battlesLost+=1;battles.splice(battles.indexOf(battle),1);}
    }
    stage=stageFor(escalation);const commandDay=day%mode.command_cycle.cycle_days<mode.command_cycle.active_days,targeted=new Set(battles.map(b=>b.target));if(commandDay){const candidates=targetOrder(frontier(controlled,targeted));while(battles.length<mode.maximum_concurrent_battles&&candidates.length){const target=candidates.shift(),origin=adjacency[target.territory_id].find(id=>controlled.has(id))||startId,enemy=config.base_enemy_power*terrainFactor(target)*urbanFactor(target)*(1+day*config.enemy_growth_per_day)*stage.enemy_power_multiplier*(1+foreignReinforcements*political.global_escalation.us_reinforcement_enemy_power);let chosen=[],fp=0,mp=0;
      for(const f of modern.filter(f=>f.status==='idle'&&!f.defected&&f.personnel>=config.minimum_modern_commitment&&f.lastRefusalDay!==day).sort((a,b)=>b.loyalty-a.loyalty).slice(0,8)){if(!accepts(f,target.territory_id,random)){f.refusals+=1;f.lastRefusalDay=day;f.loyalty-=1;modernRefusals+=1;continue;}chosen.push(f);mp+=modernPower(f,combatSupply,target.territory_id);if(mp>=enemy*strategy.attack_ratio)break;}
      if(fp+mp<enemy*strategy.attack_ratio){for(const f of future.filter(f=>f.status==='idle'&&f.personnel>=config.minimum_future_commitment).sort((a,b)=>futurePower(b,combatSupply)-futurePower(a,combatSupply))){chosen.push(f);fp+=futurePower(f,combatSupply);if(fp+mp>=enemy*strategy.attack_ratio)break;}}
      if(!chosen.length||fp+mp<enemy*.72)continue;const duration=config.base_battle_days+(['mountainous','subarctic','mixed-upland'].includes(target.terrain_class)?1:0)+(['high','very-high'].includes(target.urbanisation)?1:0),battle={id:`B-${day}-${target.territory_id}`,target:target.territory_id,origin,attackers:chosen.map(f=>f.id),enemyPower:enemy,progress:0,days:0,minimumDays:duration,casualties:{},broken:0,futurePowerAtStart:fp,modernPowerAtStart:mp};for(const f of chosen)f.status='battle';battles.push(battle);}}
    escalation=clamp(escalation,0,100);peakEscalation=Math.max(peakEscalation,escalation);
    if(controlled.size===territories.length&&battles.length===0)completed=day;
    const futureOperational=future.reduce((s,f)=>s+f.personnel,0);if(futureOperational<political.defeat_conditions.future_operational_personnel_floor)defeat='future-force-below-operational-floor';
  }
  const states={contested:0,controlled:0,administered:0,integrated:0};for(const x of controlled.values())states[occupationState(x,day)]+=1;return{mode:mode.id,strategy:strategy.id,start_territory:startId,seed_index:seedIndex,completed:completed!==null,completion_day:completed,within_target_range:completed!==null&&completed>=mode.target_turn_range[0]&&completed<=mode.target_turn_range[1],defeat,territories_controlled:controlled.size,occupation_states:states,battles_won:battlesWon,battles_lost:battlesLost,modern_led_victories:modernLed,modern_formations_raised:modern.length,modern_refusals:modernRefusals,modern_defections:modernDefections,resistance_incidents:resistanceIncidents,uprisings,lost_territories:lostTerritories,peak_escalation:Number(peakEscalation.toFixed(1)),highest_stage:stageFor(peakEscalation).id,foreign_reinforcements:foreignReinforcements,nuclear_risk_days:nuclearRiskDays,lowest_supply_percent:Number((lowestSupply*100).toFixed(1)),future:{active:future.reduce((s,f)=>s+f.personnel,0),killed:future.reduce((s,f)=>s+f.killed,0),captured:future.reduce((s,f)=>s+f.captured,0),functional_armour:future.reduce((s,f)=>s+f.full,0),damaged_armour:future.reduce((s,f)=>s+f.damaged,0),unarmoured:future.reduce((s,f)=>s+f.unarmoured,0)},modern:{active:modern.filter(f=>!f.defected).reduce((s,f)=>s+f.personnel,0),killed:modern.reduce((s,f)=>s+f.killed,0),captured:modern.reduce((s,f)=>s+f.captured,0)},technology_exposure:technologyExposure};
}

const runs=[];for(const mode of config.modes)for(const strategy of config.strategies)for(const t of territories)for(let seed=0;seed<config.seeds_per_start;seed+=1)runs.push(run(t.territory_id,mode,strategy,seed));
const summaries=[];for(const mode of config.modes)for(const strategy of config.strategies){const g=runs.filter(r=>r.mode===mode.id&&r.strategy===strategy.id),done=g.filter(r=>r.completed);summaries.push({mode:mode.id,strategy:strategy.id,runs:g.length,completion_rate_percent:Number((done.length/g.length*100).toFixed(1)),completion_day_median:done.length?percentile(done.map(r=>r.completion_day),.5):null,within_target_rate_percent:Number((g.filter(r=>r.within_target_range).length/g.length*100).toFixed(1)),territories_controlled_median:percentile(g.map(r=>r.territories_controlled),.5),battles_lost_median:percentile(g.map(r=>r.battles_lost),.5),modern_led_victories_median:percentile(g.map(r=>r.modern_led_victories),.5),modern_refusals_median:percentile(g.map(r=>r.modern_refusals),.5),modern_defections_median:percentile(g.map(r=>r.modern_defections),.5),resistance_incidents_median:percentile(g.map(r=>r.resistance_incidents),.5),peak_escalation_median:percentile(g.map(r=>r.peak_escalation),.5),highest_stage_mode:Object.entries(g.reduce((a,r)=>(a[r.highest_stage]=(a[r.highest_stage]||0)+1,a),{})).sort((a,b)=>b[1]-a[1])[0][0],nuclear_risk_run_percent:Number((g.filter(r=>r.nuclear_risk_days>0).length/g.length*100).toFixed(1)),lowest_supply_percent_median:percentile(g.map(r=>r.lowest_supply_percent),.5),future_killed_median:percentile(g.map(r=>r.future.killed),.5),future_functional_armour_median:percentile(g.map(r=>r.future.functional_armour),.5),modern_killed_median:percentile(g.map(r=>r.modern.killed),.5)});}
const report={version:'0.2',purpose:'Final foundation integration across the 101-territory campaign.',run_count:runs.length,summaries,findings:['Future and modern formations now persist through the same multi-day campaign operations.','Occupation state controls modern mobilisation and captured supply while resistance can damage or reverse control.','Global escalation changes enemy power, supply access, foreign reinforcement and strategic risk inside the same campaign loop.'],limitations:['Enemy and allied national formations remain synthetic until the dated World State package.','The reduced campaign resolver preserves validated relationships but is not the future player-facing battle implementation.','The general is exposed to strategic crisis but does not yet move independently or receive intelligence warnings.']};
const out=path.join(root,'data/generated/simulations');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'integrated-foundation-runs-v0.2.json'),`${JSON.stringify(runs,null,2)}\n`);fs.writeFileSync(path.join(out,'integrated-foundation-summary-v0.2.json'),`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report,null,2));
